language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.0
    - android-23
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

