language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    
script: gradle assembleRelease

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

